---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: contactbackendappdeployment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: contactbackend
 template:
  metadata:
   name: contactbackend
   labels:
     app: contactbackend
  spec:
    containers:
    - name: contactbackendcontainer
      image: krishna0369/backend-app
      ports:
      - containerPort: 8080
       resources:
         limits:
           cpu: 500m
         requests:
           cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
 name: contactbackendsvc
spec:
  type: LoadBalancer
  selector:
   app: contactbackend
  ports:
   - port: 80
     targetPort: 8080
---     ---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-demo-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name:  contactbackendappdeployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50

...
